export const environment = {
    version: 'agha_staging_Thu Mar 28 2019 15:29:20 GMT+1100 (Australian Eastern Daylight Time)',
    production: false,
    ci: false,
    ensemblDomain: 'grch37.rest.ensembl.org',
    ensemblProtocol: 'https',
    baseHref: '',
    auth0ClientId: 'eS2HA6aSYnxCXFvo9bzHpV1DI6H1yw0l',
    auth0Domain: 'sgc.au.auth0.com',
    auth0Connection: 'Username-Password-Authentication',
    auth0MachineClientId: '9O0wRIq6yuPaUYp7YGskT0DwFQ3C6Bvj',
    auth0MachineClientSecret: 'xcLNeH7df-f8v6tHuiHkkX8x200fB7U5oyd4WFMMOWcgqCCBrLeTQ3Rc4yuC6RYv',
    beaconNetworkUrl: 'https://beacon-network.org/api',
    // vsalUrl: 'http://localhost:3000',
    vsalUrl: 'https://sgc.garvan.org.au/ssvs/query',
    vsalUrl2: 'https://129.94.15.179/vsal/core/find',
    // elasticUrl: 'http://localhost:328v40',
    elasticUrl: 'https://dr-sgc.kccg.garvan.org.au/_elasticsearch',
    durlUrl: 'https://wt-ec1ac815dce38c76c2e7662693b82189-0.run.webtask.io/durl-dev',
    sentryUrl: 'https://90b2013bdfef4fef9491990e6ad379c6@sentry.io/158605',
    clinicalUrl: 'http://localhost:3000',
    mapd: {
        protocol: 'https',
        host: 'mapd.vectis-api.com',
        port: '443',
        dbName: 'mapd',
        user: 'mapd',
        pwd: 'HyperInteractive',
    }
};
