export const Mitochondria = ['Prof John Christodoulou', 'Prof David Thorburn', 'Prof Mike Ryan', 'Prof Alexandra Filipovska', 'Dr Joy Lee', 'Prof Martin Delayticki', 'Michelle de Silva', 'Dr Nick Smith', 'Dr Janice Fletcher', 'Anne Baxendale', 'Dr Maina Kava', 'Prof David Coman', 'Melanie Tom', 'Dr Shanti Balasubramaniam', 'Kirsten Boggs']

export const Neuromuscular = ['Prof Nigel Laing','A/Prof Chris Barnett', 'Dr Anita Cairns', 'A/Prof Sandra Cooper', 'Dr Mark Davis', 'Dr Roula Ghaoui', 'A/Prof Kristi Jones', 'Prof Phillipa Lamont', 'Dr Suzanna MacLennon', 'Dr David Mowat', 'A/Prof Kristen Nowak', 'A/Prof Gina Ravenscroft', 'Prof Monique Ryan', 'Denise Howting']

export const Acutecare = ['A/Prof Zornitza Stark','Dr Sebastian Lunke', 'Prof John Christodoulou', 'Dr Emma Krzesinski', 'Dr Matthew Hunter', 'A/Prof Sue White', 'Dr Tiong Tan', 'Dr Katherine Howell', 'Dr Lauren Akesson', 'Dr Andrew Fennell', 'Dr Joy Lee', 'Dr Heidi Peters', 'Dr Michelle De Silva', 'Sam Ayres', 'Gemma Brett', 
'Ivan Macciocca', 'Lyndon Gallacher', 'Dr Amanda Moody', 'Dr George McGillivray', 'Dr Anand Vasudevan', 'Anna Jarmolowicz', 'Anne Baxendale', 'A/Prof Christiane Theda', 'Ella Wilkins', 'Dr Jason Pinner', 'Dr Sarah Sandaradura', 'A/Prof Meredith Wilson', 'Kirsten Boggs', 'Dr Ben Lundie', 'A/Prof Michael Buckley', 'A/Prof Tony Roscioli', 
'Prof Edwin Kirk', 'Dr Annie Bye', 'Dr David Mowat', 'Dr Kevin Swil', 'Dr Meredith Ward', 'Dr Amit Trivedi', 'Dr Kaustuv Bhattacharya', 'Dr Lisa Ewans', 'Ron Fleischer', 'Dr Yemima Berman', 'Dr Mary Louise Freckmann', 'Dr Himanshu Goel', 'Dr Nick Pigott', 'Dr Chirag Patel', 'A/Prof Julie McGaughran', 'Michael Quinn', 'Melanie Tom', 
'Prof David Coman', 'Dr Deepa Srinivasan', 'Prof Luregn Schlapbach', 'Dr Katherine White', 'A/Prof Chris Barnett', 'Prof Jozef Gecz', 'Sarah Borrie', 'Sarah King Smith', 'A/Prof Clara Gaff', 'Dr Belinda Mclaren', 'Dr Amy Nisselle', 'Fiona Lynch', 'Dr Melissa Martyn', 'Dr Ilias Goranitis', 'A/Prof Ainsley Newson', 'Prof Julian Savulescu', 
'Dr Chris Gyngell', 'Prof Dominic Wilkinson', 'Prof Jeffrey Braithwaite', 'Dr Stephanie Best', 'Dr Janet Long']
